# Generated by Django 4.2.1 on 2023-07-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=30)),
                ('dese', models.TextField(max_length=500)),
                ('Phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
