# Generated by Django 4.2.1 on 2023-07-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('catagory', models.CharField(default='', max_length=30)),
                ('prise', models.IntegerField(default=0)),
                ('dese', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/image')),
            ],
        ),
    ]
