# Generated by Django 4.2.1 on 2023-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=500)),
                ('Phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
